[package]
name = "codesearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.5"
hmac-sha256 = "1.1.6"
home = "0.5.4"
ignore = "0.4.20"
indicatif = "0.17.3"
